# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

### 1\. 
Create a random list of number and then save it to a text file named "simple_data.txt"

In [31]:
import numpy.random as npr

arr = npr.rand(10)*10   # array di numeri casuali da 0 a 10
arr = arr.T
print(arr)

# modo 1:
np.savetxt("simple_data_01.txt", arr)

# modo 2:
with open("simple_data.txt", 'w') as fin:
    for i in arr:
        fin.write(str(i) + '\n')

[6.86119404 5.06773296 1.72433246 3.07643498 8.35781668 1.47159411
 1.95435897 0.21904451 2.29750536 8.20817512]


### 2\. 
Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [41]:
mat = npr.rand(5,5)
print(mat)
print(type(mat.shape))

np.savetxt("mat_data.txt", mat)

[[0.26725316 0.70459998 0.77566095 0.13228236 0.83395699]
 [0.32406585 0.12912702 0.22742923 0.11800206 0.94578397]
 [0.36522023 0.2307668  0.05314463 0.89188478 0.9587138 ]
 [0.7069211  0.94597015 0.55099567 0.92578318 0.39356539]
 [0.22638508 0.02304337 0.78597597 0.70289775 0.92470272]]
<class 'tuple'>


### 3\. 
Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [45]:
# modo 1:
with open("mat_data.csv", "w") as fin:
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            fin.write(str(mat[i,j]) + ",")
        fin.write("\n")

# modo 2:
import csv
with open("prova.csv", "w") as fout:
    writer = csv.writer(fout)
    writer.writerow(mat)  # Scrive tutti gli elementi in una singola riga

# modo 3:
np.savetxt("prova_2.csv", mat, delimiter=",")

### 4\. 
Load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [7]:
with open("credit_card.dat", "r") as f:
    # print(f.read())
    credit_card = []
    word = f.readline()
    # print(type(word))
    max = len(word)   # len = 119 
    numeri_su_riga = max // 6
    for i in range(numeri_su_riga):   
        credit_card.append( str(word[i:i+6]) )
        word = f.readline()
print(credit_card)

# list = []
# for i in range(len(credit_card)):
#     list.append (  int(credit_card[i],2)  )
# print(list)

list = []
for i in range(len(credit_card)):
    list.append ( chr( int(credit_card[i] ) ))
print(list)

print(chr(110111))


['110111', '100111', '001011', '000110', '001101', '111100', '110111', '100011', '011111', '100110', '101100', '011010', '110001', '101001', '001111', '000110', '111100', '011100', '110100']
['\U0001ae1f', '𘜏', 'ϳ', 'n', 'э', '𛇼', '\U0001ae1f', '𘚫', '⭧', '𘜎', '𘫬', '⬂', '\U0001adb1', '𘪉', 'ї', 'n', '𛇼', '⭜', '\U0001ae14']
𚸟


5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.